import * as url from 'url'

import { parseSignatureHeader } from './util/parser'
import { sign } from './util/signature'
import { hasEpochExpired, isSignatureHeaderValid } from './util/webhooks'
import { MissingSecretKeyError, WebhookAuthenticateError } from './errors'

export default class Webhooks {
  getPublicKeys: (keyId?: string) => Promise<string[]>
  secretKey?: string

  constructor({
    getPublicKeys,
    secretKey,
  }: {
    getPublicKeys: (keyId?: string) => Promise<string[]>
    secretKey?: string
  }) {
    this.getPublicKeys = getPublicKeys
    this.secretKey = secretKey
  }

  /**
   * Injects the webhook public key for authentication
   * @param header X-FormSG-Signature header
   * @param uri The endpoint that FormSG is POSTing to
   * @returns true if the header is verified
   * @throws {WebhookAuthenticateError} If the signature or uri cannot be verified
   */
  authenticate = async (header: string, uri: string) => {
    // Parse the header
    const signatureHeader = parseSignatureHeader(header)
    const {
      v1: signature,
      t: epoch,
      s: submissionId,
      f: formId,
      kid: keyId,
    } = signatureHeader

    // Get fresh public keys on each signature verification, and try to get keyId if provided
    const publicKeys = await this.getPublicKeys(keyId)

    // If keyId isn't provided. Try each public key until one works or all fail
    for (const publicKey of publicKeys) {
      if (isSignatureHeaderValid(uri, signatureHeader, publicKey)) {
        if (!hasEpochExpired(epoch)) {
          return true
        }
        // If epoch expired, no need to try other keys
        throw new WebhookAuthenticateError(
          `Signature is not recent for uri=${uri} submissionId=${submissionId} formId=${formId} epoch=${epoch} signature=${signature}`
        )
      }
    }

    throw new WebhookAuthenticateError(
      `Signature could not be verified for uri=${uri} submissionId=${submissionId} formId=${formId} epoch=${epoch} signature=${signature}`
    )
  }

  /**
   * Generates a signature based on the URI, submission ID and epoch timestamp.
   * @param params The parameters needed to generate the signature
   * @param params.uri Full URL of the request
   * @param params.submissionId Submission Mongo ObjectId saved to the database
   * @param params.epoch Number of milliseconds since Jan 1, 1970
   * @returns the generated signature
   * @throws {MissingSecretKeyError} if a secret key is not provided when instantiating this class
   * @throws {TypeError} if any parameters are undefined
   */
  generateSignature = ({
    uri,
    submissionId,
    formId,
    epoch,
  }: {
    uri: string
    submissionId: string
    formId: string
    epoch: number
  }) => {
    if (!this.secretKey) {
      throw new MissingSecretKeyError()
    }

    if (!submissionId || !uri || !formId || !epoch) {
      throw new TypeError(
        'submissionId, uri, formId, or epoch must be provided to generate a webhook signature'
      )
    }

    const baseString = `${
      url.parse(uri).href
    }.${submissionId}.${formId}.${epoch}`
    return sign(baseString, this.secretKey)
  }

  /**
   * Constructs the `X-FormSG-Signature` header
   * @param params The parameters needed to construct the header
   * @param params.epoch Epoch timestamp
   * @param params.submissionId Mongo ObjectId
   * @param params.formId Mongo ObjectId
   * @param params.signature A signature generated by the generateSignature() function
   * @returns The `X-FormSG-Signature` header
   * @throws {Error} if a secret key is not provided when instantiating this class
   */
  constructHeader = ({
    epoch,
    submissionId,
    formId,
    signature,
    keyId,
  }: {
    epoch: number
    submissionId: string
    formId: string
    signature: string
    keyId?: string
  }) => {
    if (!this.secretKey) {
      throw new MissingSecretKeyError()
    }

    const header = `t=${epoch},s=${submissionId},f=${formId},v1=${signature}`
    if (keyId) {
      return `${header},kid=${keyId}`
    }

    return header
  }
}
